### ISSUE TITLE
Todo: RecipientSubmissionWidget isWaiting/isPending logic

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#381]
- [x]  Remove estimatedGasFee code 🙂
- [x]  Boolean logic needs revisiting. Only partially implemented.
    - Sam: I think we can use same approach as ContributionModal - `waitForTransaction` then push them to success page w/ tx hash. On that page is where we have the "pending" tx state with the tx receipt component
- [x]  Update this to use tx receipt component
- [x] Remove isWrongNetwork logic

```jsx
isWaiting = false // TODO add logic
isPending = false // TODO add logic
// TODO where to make isPending vs. isWaiting? In waitForTransaction?
// Check out Launchpad repo to view transaction states
isWrongNetwork = false // TODO remove? WalletWidget can handle this?
isTxRejected = false // TODO add logic
```

**Comment by samajammin** [comment]
@corwintines while you're working on this - I noticed this console error when adding a project to the current testnet round:

```
vue.runtime.esm.js?e832:619 [Vue warn]: Property or method "isWrongNetwork" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <RecipientSubmissionWidget> at src/components/RecipientSubmissionWidget.vue
       <JoinView> at src/views/Join.vue
         <Clr.fund> at src/App.vue
           <Root>
```

**Comment by samajammin** [comment]
Looks like we're referencing `isWrongNetwork` in this component but we don't define it anywhere 😬

**Comment by samajammin** [comment]
I suppose we can remove that entirely since:
- When a user connects, we switch them to the correct network (at least for MetaMask)
- If a user changes networks, we disconnect them
