### ISSUE TITLE
Todo: Clean up Cart

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#404]
```html

<!-- TODO: should probably only appear if more than 1 item in cart -->

<!--  TODO: Also, add getter for pre-contribution phase -->
<!-- REMOVING FOR NOW WHILE WE DON'T HAVE A JOIN PHASE: <div.../> -->

<!-- TODO: reallocation bar -->
```

```jsx
	} else if (this.isGreaterThanInitialContribution()) {
		return `Your new total can't be more than your original ${this.formatAmount(this.contribution)} contribution.`
// TODO: need to turn this into a small number

// TODO: Check that we are pre-reallocation phase
	// Double check logic with Contribute button
```

- [x]  Check logic for options like "Remove all" "split evenly" for when user only has one item in cart
- [x]  Update/double-check phase conditionals/getters
- [x]  Update with Join-only content

**Comment by corwintines** [comment]
Reallocation bar was ditched in grooming session.

I dont think we need to worry about the small number anymore, we have done a decent amount of work around that formatAmount function that handles this.
